-- Tabla cliente
CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY,
    NOMBRE VARCHAR2(255) NOT NULL,
    APELLIDO VARCHAR2(255) NOT NULL,
    CEDULA VARCHAR2(255) NOT NULL,
    GENERO VARCHAR2(255) NOT NULL,
    NACIONALIDAD VARCHAR2(255) NOT NULL,
    FECHA_NACIMIENTO VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL,
    ESTADOCIVIL VARCHAR2(255) NOT NULL,
    PROPOSITO VARCHAR2(255) NOT NULL,
    DIRECCION VARCHAR2(255) NOT NULL,
    NOMBREEMPRESA VARCHAR2(255),
    CARGO VARCHAR2(255),
    DIRECCIONEMPRESA VARCHAR2(255),
    DOCUMENTODOCUMENTOIDENTIDAD BLOB,
    DOCUMENTOPASAPORTE BLOB,
    DOCUMENTOVISA BLOB,
    DOCUMENTOORDEN BLOB
);

-- Tabla empleado
CREATE TABLE EMPLEADO (
    ID INT PRIMARY KEY,
    USUARIO VARCHAR2(50),
    CONTRASENA VARCHAR2(50),
    DNI VARCHAR2(20)
);

-- Tabla vuelo
CREATE TABLE VUELO (
    ID NUMBER PRIMARY KEY,
    NUMEROVUELO VARCHAR2(50),
    FECHASALIDA VARCHAR(50),
    HORASALIDA VARCHAR2(50),
    ORIGEN VARCHAR2(50),
    DESTINO VARCHAR2(50),
    GUAYAQUIL DURACION VARCHAR2(50),
    ESCALAS VARCHAR2(50),
    CLASE VARCHAR2(50),
    PRECIO VARCHAR2(50)
);

-- Tabla itinerario
CREATE TABLE ITINERARIO (
    ID NUMBER PRIMARY KEY,
    DESCRIPCION VARCHAR2(100),
    DURACION VARCHAR2(50),
    PAISORIGEN VARCHAR2(50),
    CIUDADORIGEN VARCHAR2(50),
    PAISDESTINO VARCHAR2(50),
    GUAYAQUIL CIUDADDESTINO VARCHAR2(50)GUAYAQUIL
);

-- Tabla tarifa
CREATE TABLE TARIFA (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    MONTO VARCHAR2(50),
    RESTRICCIONES VARCHAR2(100),
    VUELO_ID NUMBER,
    CONSTRAINT FK_TARIFA_VUELO FOREIGN KEY (VUELO_ID) REFERENCES VUELO(ID)
);

-- Tabla factura
CREATE TABLE FACTURA (
    ID NUMBER PRIMARY KEY,
    FECHAFACTURA VARCHAR2(50),
    MONTOTOTAL VARCHAR2(50),
    METODOPAGO VARCHAR2(50),
    ESTADOPAGO VARCHAR2(50),
    RESERVA_ID NUMBER,
    CONSTRAINT FK_FACTURA_RESERVA FOREIGN KEY (RESERVA_ID) REFERENCES RESERVA(ID)
);